//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engage.Dnn.Dashboard {
    
    
    public partial class Host {
        
        /// <summary>
        /// AboutDatabaseSizeLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink AboutDatabaseSizeLink;
        
        /// <summary>
        /// DatabaseLogSizeItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.DashboardItem DatabaseLogSizeItem;
        
        /// <summary>
        /// DatabaseSizeItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.DashboardItem DatabaseSizeItem;
        
        /// <summary>
        /// AboutDatabaseSizeMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.ModuleMessage AboutDatabaseSizeMessage;
        
        /// <summary>
        /// AboutBackupHistoryLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink AboutBackupHistoryLink;
        
        /// <summary>
        /// BackupHistoryItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.DashboardItem BackupHistoryItem;
        
        /// <summary>
        /// BackupHistoryPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel BackupHistoryPanel;
        
        /// <summary>
        /// BackupHistoryGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView BackupHistoryGridView;
        
        /// <summary>
        /// AboutBackupHistoryMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.ModuleMessage AboutBackupHistoryMessage;
        
        /// <summary>
        /// AboutLogRecordsLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink AboutLogRecordsLink;
        
        /// <summary>
        /// NumberOfEventLogRecordsItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.DashboardItem NumberOfEventLogRecordsItem;
        
        /// <summary>
        /// NumberOfSiteLogRecordsItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.DashboardItem NumberOfSiteLogRecordsItem;
        
        /// <summary>
        /// AboutLogRecordsMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.ModuleMessage AboutLogRecordsMessage;
        
        /// <summary>
        /// AboutScheduledProcessesLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink AboutScheduledProcessesLink;
        
        /// <summary>
        /// NumberOfFailedScheduleProcessesItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.DashboardItem NumberOfFailedScheduleProcessesItem;
        
        /// <summary>
        /// AboutScheduledProcessesMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.ModuleMessage AboutScheduledProcessesMessage;
        
        /// <summary>
        /// AboutUnusedModulesLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink AboutUnusedModulesLink;
        
        /// <summary>
        /// ModulesNotInUseItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.DashboardItem ModulesNotInUseItem;
        
        /// <summary>
        /// UnusedModulesPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel UnusedModulesPanel;
        
        /// <summary>
        /// ModulesNotInUseGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView ModulesNotInUseGridView;
        
        /// <summary>
        /// AboutUnusedModulesMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Engage.Dnn.Dashboard.ModuleMessage AboutUnusedModulesMessage;
    }
}
